CREATE TABLE Users
(
    Id INT PRIMARY KEY IDENTITY(1,1),

    FullName NVARCHAR(100) NOT NULL,

    Email NVARCHAR(100) UNIQUE NOT NULL,

    PasswordHash NVARCHAR(255) NOT NULL,

    UserRole NVARCHAR(50) NOT NULL,

    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);